# Name of the domain bridge, used for node naming and logging
name: my_bridge
from_domain: 28
to_domain: 27
topics:
  # Bridge "/clock" topic from doman ID 28 to domain ID 37
  clock:
    type: rosgraph_msgs/msg/Clock
  # Bridge "/chatter" topic from doman ID 2 to domain ID 3
  # /cmd_vel:
  #   type: geometry_msgs/msg/Twist
  #   # Override QoS reliablity setting to be best effort
  #   # This affects the domain bridge subscription and publisher
  #   # This does NOT affect the other "chatter" bridge below, which is for a different domain
  #   qos:
  #     reliability: reliable
  /rigid_bodies:
      type: mocap_msgs/msg/RigidBodies
      # Reverse 'from' and 'to' domains 
      reversed: True
  # /robot_4/cmd_vel:
  #     type: geometry_msgs/msg/Twist
  #     qos:
  #       reliability: reliable